import globals from "globals";

// Имена, объявленные в одном файле js/ и используемые в других.
// Скрипты подключаются обычными <script> без модулей, поэтому всё
// живёт в одной глобальной области — для ESLint это надо перечислить
// явно, иначе no-undef ругался бы на каждое обращение.
// Список сгенерирован из объявлений верхнего уровня в js/*.js.
const sharedBrowserGlobals = [
  "accentVariants",
  "activeStatusBuckets",
  "activeTierCollections",
  "animateCounters",
  "animateStackedBars",
  "applyNavLabels",
  "applyRvFilters",
  "applyTabPreferences",
  "applyTheme",
  "bindCompare",
  "bindRvFilters",
  "buildMyPassport",
  "BUILTIN_CAT_KEYS",
  "BUILTIN_TAG_NAMES",
  "cache",
  "CAT_COLORS",
  "CAT_LABELS",
  "closeCollectionModal",
  "closeCollectionModalOnOverlay",
  "closeReviewModal",
  "cmpChip",
  "cmpMetaHtml",
  "cmpPosterHtml",
  "COLLAPSE_KEY",
  "collectionFileFor",
  "compareIntroHtml",
  "compareOneSidedHtml",
  "compareResultHtml",
  "compareSectionHtml",
  "compareStyles",
  "compareSummaryHtml",
  "coverFallbackAttrs",
  "DEFAULT_ACCENT",
  "DEFAULT_LABELS",
  "DEFAULT_STATUS_BUCKETS",
  "DISAGREE_THRESHOLD",
  "domReady",
  "esc",
  "exportMyPassport",
  "EXTERNAL_ID_LABELS",
  "extractIdsFromCover",
  "favPersonCard",
  "favTitleCard",
  "fetchReviews",
  "findReviewForTitle",
  "fmtDateStr",
  "getCollapsed",
  "GRADE_ORDER",
  "gradeInlineHtml",
  "gradeLabels",
  "GRADES",
  "GRADES_DEF",
  "gradeScore",
  "gradeToShelf",
  "guessRussianPlural",
  "GUEST_KEY",
  "guestPassport",
  "hexToRgb",
  "hslToHex",
  "ID_MATCH_ORDER",
  "imgFallbackAttrs",
  "indexByKeys",
  "isAdmin",
  "isFavSectionVisible",
  "isHex",
  "isStatVisible",
  "isTierModeVisible",
  "loadCharGames",
  "loadCompare",
  "loadFavorites",
  "loadHtml2Canvas",
  "loading",
  "loadNow",
  "loadReviews",
  "loadStats",
  "loadTierlist",
  "makeGradeInfo",
  "makeSection",
  "manualCard",
  "matchKeys",
  "mergeIds",
  "mergeLabels",
  "myGradeInfo",
  "normTitle",
  "NOVEL_FORMATS",
  "openCollectionModal",
  "openReviewModal",
  "PALETTE_TOKENS",
  "parsePassport",
  "PASSPORT_FORMAT",
  "PASSPORT_VERSION",
  "patchSiteSettings",
  "PH_SQ",
  "PH_TALL",
  "plural",
  "pluralLabel",
  "proxyImagesToDataUrls",
  "rebuildGradesFromScale",
  "renderAllTimeStats",
  "renderCompare",
  "renderCounters",
  "renderDonut",
  "renderFavorites",
  "renderGradeChart",
  "renderNow",
  "renderReviews",
  "renderRewatchStats",
  "renderRvFilterGroup",
  "renderStackedBarChart",
  "renderTagCloud",
  "renderTitleOfYear",
  "renderYearDigest",
  "resolveAccent",
  "reviewCard",
  "reviewModalBodyHtml",
  "rgbToHsl",
  "rvBindCardClicks",
  "rvLastFiltered",
  "rvState",
  "saveCollapsed",
  "siteLabel",
  "sortByOrder",
  "SOURCE_FILTER_ORDER",
  "SOURCE_LABELS",
  "sourceBtnHtml",
  "statsBindAll",
  "statsCompletedYear",
  "statsRender",
  "statsState",
  "statsTopTitlesOfYear",
  "statsYearFiltersHtml",
  "submitNewCollection",
  "SUBTYPE_LABELS",
  "TAG_CAT_CLASS",
  "tagHtml",
  "TAGS_MAP",
  "THEME_PRESETS",
  "themeOptions",
  "themePalette",
  "TIER_ROWS",
  "TL_TYPE_ORDER",
  "tlBindAll",
  "tlBindTooltip",
  "tlCharHeight",
  "tlCharsHtml",
  "tlExport",
  "tlFiltersHtml",
  "tlInferType",
  "tlModeToggleHtml",
  "tlMoveTip",
  "tlPresentTypes",
  "tlRender",
  "tlShowTip",
  "tlSlugify",
  "tlState",
  "tlTitlesHtml",
  "tlTooltipHtml",
  "tlTypeLabel",
  "tlYearFiltersHtml",
  "toggleSection",
  "TYPE_COLORS",
  "TYPE_FILTER_ORDER",
  "TYPE_LABELS",
  "TYPE_PLURAL",
  "unitForms",
  "updateFileBtnName",
  // подключаются с CDN по требованию
  "html2canvas",
  "JSZip",
];

const commonRules = {
  "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
  "no-undef": "error",
  eqeqeq: ["warn", "smart"],
  "no-var": "error",
  "prefer-const": "warn",
  // Пустой catch здесь — осознанный приём («нет файла — работаем на
  // значениях по умолчанию»), он встречается по коду и в комментариях
  // объяснён, ругаться на него не нужно.
  "no-empty": ["error", { allowEmptyCatch: true }],
};

export default [
  {
    // Фронтенд: обычные <script>, общая глобальная область
    files: ["js/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        ...globals.browser,
        ...Object.fromEntries(sharedBrowserGlobals.map((name) => [name, "writable"])),
      },
    },
    rules: {
      ...commonRules,
      // vars: "local" — не ругаться на функции верхнего уровня, которые
      // «нигде не используются». Половина из них вызывается из onclick=
      // в HTML, куда ESLint не заглядывает, так что иначе линтер выдавал
      // бы два десятка ложных предупреждений и его перестали бы читать.
      // Внутри функций неиспользуемые переменные по-прежнему ловятся.
      "no-unused-vars": ["warn", { vars: "local", args: "after-used", argsIgnorePattern: "^_" }],
    },
  },
  {
    // Бэкенд: Cloudflare Pages Functions — ES-модули в воркер-рантайме
    files: ["functions/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: { ...globals.worker, ...globals.browser },
    },
    rules: commonRules,
  },
  {
    // Service worker — свой набор глобальных (self, clients, caches)
    files: ["sw.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: globals.serviceworker,
    },
    rules: commonRules,
  },
];
